# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d474b782e1cdd512cde8ebfad835e55b72c5e78781a04b36a345cca6646becf26011b17a1aca8b7a9f87998cff4e12ae99c16536aa6d5495a2603efd31fe25e8

test:
  secret_key_base: 0ff35639cb0175c7fa27d158a8469286d00d0629b07ad9752cd696a9dda0bcfce1dd402340aeab85abd9df50315938354d70bd02dd960b81832b47ff1943c794

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
